CONST PI = 3.141592654#
CLS
PRINT
PRINT "  y =  sen 1/3x"
PRINT
PRINT "  x        y"
PRINT

PRINT USING "  30   -  ###.###"; SIN((1 / 3) * (30 * (PI / 180)))
PRINT USING "  45   -  ###.###"; SIN((1 / 3) * (45 * (PI / 180)))
PRINT USING "  60   -  ###.###"; SIN((1 / 3) * (60 * (PI / 180)))
PRINT USING "  90   -  ###.###"; SIN((1 / 3) * (90 * (PI / 180)))
PRINT USING " 120   -  ###.###"; SIN((1 / 3) * (120 * (PI / 180)))
PRINT USING " 135   -  ###.###"; SIN((1 / 3) * (135 * (PI / 180)))
PRINT USING " 150   -  ###.###"; SIN((1 / 3) * (150 * (PI / 180)))
PRINT USING " 180   -  ###.###"; SIN((1 / 3) * (180 * (PI / 180)))
PRINT USING " 225   -  ###.###"; SIN((1 / 3) * (225 * (PI / 180)))
PRINT USING " 240   -  ###.###"; SIN((1 / 3) * (240 * (PI / 180)))
PRINT USING " 270   -  ###.###"; SIN((1 / 3) * (270 * (PI / 180)))
PRINT USING " 300   -  ###.###"; SIN((1 / 3) * (300 * (PI / 180)))
PRINT USING " 315   -  ###.###"; SIN((1 / 3) * (315 * (PI / 180)))
PRINT USING " 330   -  ###.###"; SIN((1 / 3) * (330 * (PI / 180)))
PRINT USING " 360   -  ###.###"; SIN((1 / 3) * (360 * (PI / 180)))
PRINT
PRINT
PRINT "                            Presione una tecla..."
A$ = INPUT$(1)



CLS
PRINT
PRINT "  y = cos 1/3x"
PRINT
PRINT "  x        y"
PRINT

PRINT USING "  30   -  ###.###"; COS((1 / 3) * (30 * (PI / 180)))
PRINT USING "  45   -  ###.###"; COS((1 / 3) * (45 * (PI / 180)))
PRINT USING "  60   -  ###.###"; COS((1 / 3) * (60 * (PI / 180)))
PRINT USING "  90   -  ###.###"; COS((1 / 3) * (90 * (PI / 180)))
PRINT USING " 120   -  ###.###"; COS((1 / 3) * (120 * (PI / 180)))
PRINT USING " 135   -  ###.###"; COS((1 / 3) * (135 * (PI / 180)))
PRINT USING " 150   -  ###.###"; COS((1 / 3) * (150 * (PI / 180)))
PRINT USING " 180   -  ###.###"; COS((1 / 3) * (180 * (PI / 180)))
PRINT USING " 225   -  ###.###"; COS((1 / 3) * (225 * (PI / 180)))
PRINT USING " 240   -  ###.###"; COS((1 / 3) * (240 * (PI / 180)))
PRINT USING " 270   -  ###.###"; COS((1 / 3) * (270 * (PI / 180)))
PRINT USING " 300   -  ###.###"; COS((1 / 3) * (300 * (PI / 180)))
PRINT USING " 315   -  ###.###"; COS((1 / 3) * (315 * (PI / 180)))
PRINT USING " 330   -  ###.###"; COS((1 / 3) * (330 * (PI / 180)))
PRINT USING " 360   -  ###.###"; COS((1 / 3) * (360 * (PI / 180)))
PRINT
PRINT
PRINT "                            Presione una tecla..."
A$ = INPUT$(1)



CLS
PRINT
PRINT "  y = tan 1/3x"
PRINT
PRINT "  x        y"
PRINT

PRINT USING "  30   -  ###.###"; TAN((1 / 3) * (30 * (PI / 180)))
PRINT USING "  45   -  ###.###"; TAN((1 / 3) * (45 * (PI / 180)))
PRINT USING "  60   -  ###.###"; TAN((1 / 3) * (60 * (PI / 180)))
PRINT USING "  90   -  ###.###"; TAN((1 / 3) * (90 * (PI / 180)))
PRINT USING " 120   -  ###.###"; TAN((1 / 3) * (120 * (PI / 180)))
PRINT USING " 135   -  ###.###"; TAN((1 / 3) * (135 * (PI / 180)))
PRINT USING " 150   -  ###.###"; TAN((1 / 3) * (150 * (PI / 180)))
PRINT USING " 180   -  ###.###"; TAN((1 / 3) * (180 * (PI / 180)))
PRINT USING " 225   -  ###.###"; TAN((1 / 3) * (225 * (PI / 180)))
PRINT USING " 240   -  ###.###"; TAN((1 / 3) * (240 * (PI / 180)))
PRINT USING " 270   -  ###.###"; TAN((1 / 3) * (270 * (PI / 180)))
PRINT USING " 300   -  ###.###"; TAN((1 / 3) * (300 * (PI / 180)))
PRINT USING " 315   -  ###.###"; TAN((1 / 3) * (315 * (PI / 180)))
PRINT USING " 330   -  ###.###"; TAN((1 / 3) * (330 * (PI / 180)))
PRINT USING " 360   -  ###.###"; TAN((1 / 3) * (360 * (PI / 180)))
PRINT
PRINT
PRINT "                            Presione una tecla..."
A$ = INPUT$(1)



CLS
PRINT
PRINT "  y = cot 1/3x"
PRINT
PRINT "  x        y"
PRINT

PRINT USING "  30   -  ###.###"; (1 / TAN((1 / 3) * (30 * (PI / 180))))
PRINT USING "  45   -  ###.###"; (1 / TAN((1 / 3) * (45 * (PI / 180))))
PRINT USING "  60   -  ###.###"; (1 / TAN((1 / 3) * (60 * (PI / 180))))
PRINT USING "  90   -  ###.###"; (1 / TAN((1 / 3) * (90 * (PI / 180))))
PRINT USING " 120   -  ###.###"; (1 / TAN((1 / 3) * (120 * (PI / 180))))
PRINT USING " 135   -  ###.###"; (1 / TAN((1 / 3) * (135 * (PI / 180))))
PRINT USING " 150   -  ###.###"; (1 / TAN((1 / 3) * (150 * (PI / 180))))
PRINT USING " 180   -  ###.###"; (1 / TAN((1 / 3) * (180 * (PI / 180))))
PRINT USING " 225   -  ###.###"; (1 / TAN((1 / 3) * (225 * (PI / 180))))
PRINT USING " 240   -  ###.###"; (1 / TAN((1 / 3) * (240 * (PI / 180))))
PRINT USING " 270   -  ###.###"; (1 / TAN((1 / 3) * (270 * (PI / 180))))
PRINT USING " 300   -  ###.###"; (1 / TAN((1 / 3) * (300 * (PI / 180))))
PRINT USING " 315   -  ###.###"; (1 / TAN((1 / 3) * (315 * (PI / 180))))
PRINT USING " 330   -  ###.###"; (1 / TAN((1 / 3) * (330 * (PI / 180))))
PRINT USING " 360   -  ###.###"; (1 / TAN((1 / 3) * (360 * (PI / 180))))
PRINT
PRINT
PRINT "                            Presione una tecla..."
A$ = INPUT$(1)




CLS
PRINT
PRINT "  y = csc 1/3x"
PRINT
PRINT "  x        y"
PRINT

PRINT USING "  30   -  ###.###"; (1 / SIN((1 / 3) * (30 * (PI / 180))))
PRINT USING "  45   -  ###.###"; (1 / SIN((1 / 3) * (45 * (PI / 180))))
PRINT USING "  60   -  ###.###"; (1 / SIN((1 / 3) * (60 * (PI / 180))))
PRINT USING "  90   -  ###.###"; (1 / SIN((1 / 3) * (90 * (PI / 180))))
PRINT USING " 120   -  ###.###"; (1 / SIN((1 / 3) * (120 * (PI / 180))))
PRINT USING " 135   -  ###.###"; (1 / SIN((1 / 3) * (135 * (PI / 180))))
PRINT USING " 150   -  ###.###"; (1 / SIN((1 / 3) * (150 * (PI / 180))))
PRINT USING " 180   -  ###.###"; (1 / SIN((1 / 3) * (180 * (PI / 180))))
PRINT USING " 225   -  ###.###"; (1 / SIN((1 / 3) * (225 * (PI / 180))))
PRINT USING " 240   -  ###.###"; (1 / SIN((1 / 3) * (240 * (PI / 180))))
PRINT USING " 270   -  ###.###"; (1 / SIN((1 / 3) * (270 * (PI / 180))))
PRINT USING " 300   -  ###.###"; (1 / SIN((1 / 3) * (300 * (PI / 180))))
PRINT USING " 315   -  ###.###"; (1 / SIN((1 / 3) * (315 * (PI / 180))))
PRINT USING " 330   -  ###.###"; (1 / SIN((1 / 3) * (330 * (PI / 180))))
PRINT USING " 360   -  ###.###"; (1 / SIN((1 / 3) * (360 * (PI / 180))))
PRINT
PRINT
PRINT "                            Presione una tecla..."
A$ = INPUT$(1)



CLS
PRINT
PRINT "  y = sec 1/3x"
PRINT
PRINT "  x        y"
PRINT

PRINT USING "  30   -  ###.###"; (1 / COS((1 / 3) * (30 * (PI / 180))))
PRINT USING "  45   -  ###.###"; (1 / COS((1 / 3) * (45 * (PI / 180))))
PRINT USING "  60   -  ###.###"; (1 / COS((1 / 3) * (60 * (PI / 180))))
PRINT USING "  90   -  ###.###"; (1 / COS((1 / 3) * (90 * (PI / 180))))
PRINT USING " 120   -  ###.###"; (1 / COS((1 / 3) * (120 * (PI / 180))))
PRINT USING " 135   -  ###.###"; (1 / COS((1 / 3) * (135 * (PI / 180))))
PRINT USING " 150   -  ###.###"; (1 / COS((1 / 3) * (150 * (PI / 180))))
PRINT USING " 180   -  ###.###"; (1 / COS((1 / 3) * (180 * (PI / 180))))
PRINT USING " 225   -  ###.###"; (1 / COS((1 / 3) * (225 * (PI / 180))))
PRINT USING " 240   -  ###.###"; (1 / COS((1 / 3) * (240 * (PI / 180))))
PRINT USING " 270   -  ###.###"; (1 / COS((1 / 3) * (270 * (PI / 180))))
PRINT USING " 300   -  ###.###"; (1 / COS((1 / 3) * (300 * (PI / 180))))
PRINT USING " 315   -  ###.###"; (1 / COS((1 / 3) * (315 * (PI / 180))))
PRINT USING " 330   -  ###.###"; (1 / COS((1 / 3) * (330 * (PI / 180))))
PRINT USING " 360   -  ###.###"; (1 / COS((1 / 3) * (360 * (PI / 180))))
PRINT
PRINT
PRINT "                            Presione una tecla..."
A$ = INPUT$(1)

